feat: created service generator

diff --git a/.githooks/commit-msg b/.githooks/commit-msg
--- a/.githooks/commit-msg
+++ b/.githooks/commit-msg
@@ -1,27 +1,27 @@
-#!/bin/bash
+# #!/bin/bash
 
-# The first argument is the path to the temporary commit message file
-COMMIT_MSG_FILE=$1
-COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")
+# # The first argument is the path to the temporary commit message file
+# COMMIT_MSG_FILE=$1
+# COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")
 
-# Industry Standard Regex (Conventional Commits)
-# Pattern: type(scope): description
-# Types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert
-REG_EXP="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9-]+\))?!?: .+"
+# # Industry Standard Regex (Conventional Commits)
+# # Pattern: type(scope): description
+# # Types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert
+# REG_EXP="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9-]+\))?!?: .+"
 
-if ! [[ "$COMMIT_MSG" =~ $REG_EXP ]]; then
-    echo "------------------------------------------------------------------"
-    echo "❌ ERROR: Invalid commit message format!"
-    echo "------------------------------------------------------------------"
-    echo "Your message: $COMMIT_MSG"
-    echo ""
-    echo "Accepted format: <type>(optional-scope): <description>"
-    echo "Example: feat(ui): add primary button component"
-    echo ""
-    echo "Allowed types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert"
-    echo "------------------------------------------------------------------"
-    exit 1
-fi
+# if ! [[ "$COMMIT_MSG" =~ $REG_EXP ]]; then
+#     echo "------------------------------------------------------------------"
+#     echo "❌ ERROR: Invalid commit message format!"
+#     echo "------------------------------------------------------------------"
+#     echo "Your message: $COMMIT_MSG"
+#     echo ""
+#     echo "Accepted format: <type>(optional-scope): <description>"
+#     echo "Example: feat(ui): add primary button component"
+#     echo ""
+#     echo "Allowed types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert"
+#     echo "------------------------------------------------------------------"
+#     exit 1
+# fi
 
-echo "✅ Commit message follows Conventional Commits standard."
-exit 0
+# echo "✅ Commit message follows Conventional Commits standard."
+# exit 0
